server:
  port: 8006

spring:
  application:
    name: cloud-provider-payment-consul


  ####consul注册中心地址
  cloud:
    consul:
#      host: 192.168.122.123 #虚拟机IP地址
      host: localhost
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
