server:
  port: 3344


spring:
  #rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  application:
    name: cloud-config-server  #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xia-chao625/springcloud-alibaba-config.git  #Gitee上面的git仓库名字
          ####搜索目录
          search-paths:
            - springcloud-alibaba-config
          force-pull: true
          username: 18856589282
          password: xc135cs0625
      label: main


eureka:
  client:
    service-url:
        defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka



##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'

