server:
  port: 81

eureka:
  client:
    register-with-eureka: true
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka  #集群版本


logging:
  level:
    com.xiachao.springcloud.service.PaymentFeignService: debug
